# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

displayName: "Continuous Integration"

trigger:
  - ready/*

pool:
  vmImage: "ubuntu-latest"

steps:
  - checkout: self
    persistCredentials: true
  - task: Gradle@2
    inputs:
      workingDirectory: ""
      gradleWrapperFile: "gradlew"
      gradleOptions: "-Xmx3072m"
      javaHomeOption: "JDKVersion"
      jdkVersionOption: "1.8"
      jdkArchitectureOption: "x64"
      publishJUnitResults: true
      testResultsFiles: "**/TEST-*.xml"
      tasks: "test"
  - script: |
      git rebase origin/master
      git branch master
      git push origin master:master
      git push origin :$(Build.SourceBranch)
    displayName: "Merge to master"
