# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: Continuous Integration

trigger:
  - ready/*

pool:
  vmImage: "ubuntu-latest"

steps:
  - checkout: self
    persistCredentials: true
  #  - task: Gradle@2
  #    inputs:
  #      workingDirectory: ""
  #      gradleWrapperFile: "gradlew"
  #      gradleOptions: "-Xmx3072m"
  #      javaHomeOption: "JDKVersion"
  #      jdkVersionOption: "1.8"
  #      jdkArchitectureOption: "x64"
  #      publishJUnitResults: true
  #      testResultsFiles: "**/TEST-*.xml"
  #      tasks: "test"
  - bash: git branch -v
  - bash: git rebase origin/main
  - bash: git branch main
  - bash: git push origin main:main
  - bash: git push origin :${GITHUB_REF#refs/heads/}
